# Generated by Django 5.1.1 on 2024-10-04 07:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Conc_levels',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('conc_level_name', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('project_name', models.TextField()),
                ('project_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='SampleTypes',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('sample_type_name', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Metabolites',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('metabolite_name', models.TextField()),
                ('conc_level_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='QCapp.conc_levels')),
            ],
        ),
        migrations.CreateModel(
            name='Batches',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('batch_num', models.TextField()),
                ('batch_date', models.DateField()),
                ('batch_normalized', models.BooleanField()),
                ('project_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='QCapp.projects')),
            ],
        ),
        migrations.CreateModel(
            name='Samples',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('batch_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='QCapp.batches')),
                ('sample_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='QCapp.sampletypes')),
            ],
        ),
        migrations.CreateModel(
            name='Metabolites_conc',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('concentration', models.FloatField()),
                ('metabolite_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='QCapp.metabolites')),
                ('sample_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='QCapp.samples')),
            ],
        ),
    ]
