# Generated by Django 5.1.1 on 2024-10-27 18:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QCapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Groups',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('group_name', models.TextField()),
            ],
            options={
                'db_table': 'groups',
            },
        ),
        migrations.RemoveField(
            model_name='metabolites',
            name='conc_level_id',
        ),
        migrations.RemoveField(
            model_name='samples',
            name='sample_type',
        ),
        migrations.AddField(
            model_name='samples',
            name='sample_name',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='batches',
            name='batch_num',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='batches',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='batches',
            name='project_id',
            field=models.ForeignKey(db_column='project_id', on_delete=django.db.models.deletion.CASCADE, to='QCapp.projects'),
        ),
        migrations.AlterField(
            model_name='metabolites',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='metabolites_conc',
            name='concentration',
            field=models.FloatField(db_column='concentration'),
        ),
        migrations.AlterField(
            model_name='metabolites_conc',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='metabolites_conc',
            name='metabolite_id',
            field=models.ForeignKey(db_column='metabolite_id', on_delete=django.db.models.deletion.CASCADE, to='QCapp.metabolites'),
        ),
        migrations.AlterField(
            model_name='metabolites_conc',
            name='sample_id',
            field=models.ForeignKey(db_column='sample_id', on_delete=django.db.models.deletion.CASCADE, to='QCapp.samples'),
        ),
        migrations.AlterField(
            model_name='projects',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='samples',
            name='batch_id',
            field=models.ForeignKey(db_column='batch_id', on_delete=django.db.models.deletion.CASCADE, to='QCapp.batches'),
        ),
        migrations.AlterField(
            model_name='samples',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterModelTable(
            name='batches',
            table='batches',
        ),
        migrations.AlterModelTable(
            name='metabolites',
            table='metabolites',
        ),
        migrations.AlterModelTable(
            name='projects',
            table='projects',
        ),
        migrations.AlterModelTable(
            name='samples',
            table='samples',
        ),
        migrations.AddField(
            model_name='samples',
            name='group_id',
            field=models.ForeignKey(db_column='group_id', default=1, on_delete=django.db.models.deletion.CASCADE, to='QCapp.groups'),
        ),
        migrations.DeleteModel(
            name='Conc_levels',
        ),
        migrations.DeleteModel(
            name='SampleTypes',
        ),
    ]
